# 服务器端口，如果不配置默认是8080端口
server:
  port: 8081
# 数据库设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.36.112.232:3306/youtube_income?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: xinku
    password: wjsn0225fighting

